# Generated by Django 4.2.23 on 2025-07-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_characterclass_feat_item_spell_alter_character_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='AbilityScore',
        ),
    ]
