# Generated by Django 4.2.23 on 2025-07-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_character_charisma_character_constitution_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CharacterClass',
            new_name='Class',
        ),
    ]
